// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywgtrvamrzppeqvuqaed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Z3RydmFtcnpwcGVxdnVxYWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzAwOTUsImV4cCI6MjA3MTA0NjA5NX0.BbVoFLr1-0sWvlmDFVjNyDDCT56dZiLfIwz_d89M8-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});